// AUTO-GENERATED by scripts/refresh-redfin.mjs — do not edit manually.
// Source: Redfin Data Center (https://www.redfin.com/news/data-center/)
// License: free for non-commercial use with attribution.
// Run `node scripts/refresh-redfin.mjs` or trigger the GitHub Actions workflow to populate.

export interface RedfinZipEntry {
  latestMonth: string;    // "2026-04"
  medianSalePrice: number;
  pctChange12mo: number;  // e.g. 3.2 = +3.2%
  homesSold: number;
}

export const REDFIN_ZIPS: Record<string, RedfinZipEntry> = {};
